name 'example42-tartarus'
version '2.0.0'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-tartarus'
summary 'Puppet module for tartarus'
description 'This module installs and manages tartarus'
dependency 'example42/puppi', '>=2.0.0'
